# Generated by Django 2.1 on 2018-09-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=500)),
                ('href', models.CharField(max_length=255)),
                ('image_url', models.CharField(max_length=255)),
                ('posting_date', models.CharField(max_length=255)),
                ('full_news', models.CharField(max_length=10000)),
            ],
            options={
                'db_table': 'headlines',
                'managed': False,
            },
        ),
    ]
